---
abstract: 'JSON::XS compatible pure-Perl module.'
author:
  - 'Makamaka Hannyaharamitu, E<lt>makamaka[at]cpan.orgE<gt>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: JSON-PP
no_index:
  directory:
    - t
    - inc
requires:
  Scalar::Util: '1.08'
  Test::More: '0'
resources:
  bugtracker: https://github.com/makamaka/JSON-PP/issues
  repository: https://github.com/makamaka/JSON-PP
version: '4.16'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
